name: Build and Export CopypartyDockerImage_Demo

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  build-and-export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: |
          docker build -t copypartydockerimage_demo .

      - name: Export image to tar file
        run: |
          docker save copypartydockerimage_demo -o copypartydockerimage_demo.tar

      - name: Upload image tar file to Actions
        uses: actions/upload-artifact@v4
        with:
          name: copypartydockerimage_demo-artifact
          path: copypartydockerimage_demo.tar